{% set name = "libgcrypt" %}
{% set version = "1.12.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: d77f68f48879510e79a2f65977ccc68981781ea0923e5bdffac2a193ea3d660e

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make  # [unix]
    - libtool  # [unix]
  host:
    # Upstream source: https://github.com/gpg/libgcrypt/blob/libgcrypt-1.12.4/configure.ac#L77
    # but version 1.56 is not in the channel, hovewer 1.56 and 1.58 are fully backward compatible
    - libgpg-error 1.58

test:
  commands:
    - test -f $PREFIX/bin/dumpsexp
    - test -f $PREFIX/bin/hmac256
    - test -f $PREFIX/bin/mpicalc
    - test -f $PREFIX/include/gcrypt.h
    - test -f $PREFIX/lib/libgcrypt${SHLIB_EXT}  # [unix]

about:
  home: https://gnupg.org/software/index.html
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING.LIB
    - COPYING
    - LICENSES
  license_family: GPL
  summary: General purpose cryptographic library
  description: |
    Libgcrypt is a general purpose crypto library based on the code
    used in GnuPG.  Libgcrypt depends on the library `libgpg-error',
    which must be installed correctly before Libgcrypt is to be built.
  dev_url: https://github.com/gpg/libgcrypt
  doc_url: https://github.com/gpg/libgcrypt/tree/master/doc

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
