{% set name = "libgcrypt" %}
{% set version = "1.9.0" %}
{% set sha256 = "4d9ccaa5f99db59ebcb64d73f62825b05ce8a6b7f86d19178559ef84de1381cb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
   - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - libgpg-error

test:
  commands:
    - test -f $PREFIX/lib/libgcrypt.so  # [linux]
    - conda inspect linkages {{ name }}
    - conda inspect objects {{ name }}  # [osx]

about:
  home: https://gnupg.org/software/index.html
  license: GPL-2.0
  license_family: GPL2
  summary: 'a general purpose cryptographic library originally based on code from GnuPG.'

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
