{% set name = "libgcrypt" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 6ba59dd192270e8c1d22ddb41a07d95dcdbc1f0fb02d03c4b54b235814330aac

build:
  number: 0
  skip: True  # [win]
  run_exports:
   - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make     # [unix]
    - libtool  # [unix]
  host:
    - libgpg-error 1.51

test:
  commands:
    - test -f $PREFIX/bin/dumpsexp
    - test -f $PREFIX/bin/hmac256
    - test -f $PREFIX/bin/mpicalc
    - test -f $PREFIX/include/gcrypt.h 
    - test -f $PREFIX/lib/libgcrypt${SHLIB_EXT}  # [unix]

about:
  home: https://gnupg.org/software/index.html
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING.LIB
    - COPYING
    - LICENSES
  license_family: GPL
  summary: General purpose cryptographic library
  description: |
    Libgcrypt is a general purpose crypto library based on the code
    used in GnuPG.  Libgcrypt depends on the library `libgpg-error',
    which must be installed correctly before Libgcrypt is to be built.
  dev_url: https://github.com/gpg/libgcrypt
  doc_url: https://github.com/gpg/libgcrypt/tree/master/doc

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
