{% set name = "libgcrypt" %}
{% set version = "1.9.4" %}
{% set sha256 = "ea849c83a72454e3ed4267697e8ca03390aee972ab421e7df69dfe42b65caaf7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  run_exports:
   - {{ pin_subpackage('libgcrypt') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make     # [unix]
    - libtool  # [unix]
  host:
    - libgpg-error

test:
  commands:
    - test -f $PREFIX/lib/libgcrypt.so  # [linux]
    - conda inspect linkages {{ name }}
    - conda inspect objects {{ name }}  # [osx]

about:
  home: https://gnupg.org/software/index.html
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - COPYING.LIB
    - COPYING
    - LICENSES
  license_family: GPL
  summary: 'a general purpose cryptographic library originally based on code from GnuPG.'

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
