travis:
  secure:
    BINSTAR_TOKEN: gB4uhVok2SSUtaW2UnjXlOkeKMNr3e2eHhssId700h43Gv7lO2wGEKSMosbC4RxJUlh32ExCplyAQTqPV6B6iq+pDap6XcBEYee2ah5qt9JF6mXuRJ7xxd96Ueit7iSUw4ToollvrlUqq/E+pDxdNe9awL2kzcYAXzTeifxTALnkd1p9eEEbzhySv3l/TVmOgQFnEVfVNPdnslF1fCnJcyNQll7PpZZR6fm6a6MJLMbb3wgLbGxPKlPfmtYtTQLEy4Kp6bpzm5E9a29rmPntg3KPix1DdlB/MKPLhqYZe8WyjkOBSwAX77mNx/789TTKIxKYc0ZgYUZH+KyVz162KZYfGQe9XVEGGt+BK8oGIWdSgpc8SClpIBeVHjKFraKW/l7dojtdlHzajzY3fjmCpzqaXMKWshIavA4kXytlU6Xi5Of5i+6wllPLBJfR6HouzDLG0U40RZP9OYd+tKngUjIWuuC0XPuL5/e7Rj0J/019YRLA8KFLFYam61BrVu1lGjerbwQDxRFovlItQlQOmwzXp+Rl9VmlTKyhpK8RwE+DW9vitSte0RMjkOJUT04k/GC+5pBY4uFGsvMs2IM40WhDFv6leGuYsBga/5GMVUbvrpuCst2nyoHydBLNrgnWAxLASWcQOmbZy15hBiJzrTqsbO44ETdok4PDbkxzdos=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
