travis:
  secure:
    BINSTAR_TOKEN: yE8Jg8oEsAaUAJCSeEWHNTa9Yx4A10tzfX7rG1v2XQYQsfnC2j7GrSj2g8ZYv9fGcNNl9amtVHYeoOUDJT3zsPrxJgvQnNnmbVtrngs/TpOLgLZx5EWLlAM1EOm+LFcztEkpX8wc24wfWDm2BpJ7tiW7b/VHQpa/oPAmUdTvZ1JfoJ/GXzY8jclZ6JCckVQXl9oTPzB/S1z4ygnAHiOB8KW4L0jOPCo6O4kvx6QNYU5I0JAC1lrnygDohw8eYZyYEYnZk/4S8+ftOhXpg340BU6syboXHoZD2nEFikhtQgiCIeS5XQP0W4VmQ/bUUbu+agV7VCYL5nj77tNvpmZj/NzywRci58EkzzVeZSmiySnc4OMiLhxxaRqYb5Mqp+1ZNCQH8aKdzavHvS/yQptmtqTMPjKM7hs2HHIk2Ie/lexMQARapTi0T/6CvW4jPzCpG/IDPhfsYGDKxb1muulI4Zp9XXHrNxSj0DPAsoxhlh48CbHCrChXUadrDAOqUNXl3sgwnTS4IRq+4A4mT3N1Lz5k37QEfjHS1D32+ZtJ3B6ntImsmkJKOqkGkZpgLOsDnPD1z8Cqxf5Lz25TfgWQwEakmfheICklFdckIKYxc0Tll71ZqNM9VF+YiMNpSRbpA8YhkrtHXCYwHr8r5ADhshBm8Z4gr0qCRv9Y/nd8iS0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
