travis:
  secure:
    BINSTAR_TOKEN: azFNLWhbN53mODhK3nIWNWwJamEkwvTHOFxz+W2i12t9MU6Emv9d1z5F1HMdJlBg9h4dcLRtgqbUFnzsA/RUe8msq/HnGJ/Vgwh0OzOAOHkVAK5d6LQeC7ZzlV8H2V/x0+KCOJy/De/XTyxRvehVa/MJVWMesQmNISptIf+gBFvvTKwn7T1Irt46Q7loZdm67hCZXaDuoVaavGZVdZi1ERqmiUaIs73swR90ZzuGPO5TLuEP4wlxVtHFYTeqqBQzAn7rTUFnd0UqrrRN4yigh+KDv6OmEArNz/ZnCd8xW9KubO4qe426e4DBF/NYcCOJkauvAFZCvcg2EmvkW1te8R6wWFfMKW4NICDaMMLJIS/0WnzpcSPtrNZmdEo7NPJPnFzN3VoWq/YLY4Z4GCTSNlaJoLpba2DzglXrzn7xV2NyUxlWd6viEpZTsnI1TzbqTuHAA4Qy2H5YK02QN0tWZktO0q54jqjBKARBmfy7R/40jfl3EUlmqhKYRgxjWelk/qK+RzbHbBAPl1EXBV5bnzPwZnOBiIhwT8Pp5uMBqpOXowmJzHUNywrrsazS296nzG6cvQboyYeuoUaCKlWTku6C/uaJNfIKE/WSFdI8FnvGjbNPZJ71UOJ/wdcjX0bIjfVVpheZW3UMkV4kU/bFpaK8qbsP4ECljhCu18R2RcE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
